name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Runs every time you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        # Replace YOUR_REPOSITORY_NAME with your actual repo name
        run: flutter build web --release --base-href "/flutter_billshare/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # The folder the action should deploy
          branch: gh-pages # The branch the action should deploy to
